allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  msw: true
  sharp: true

minimumReleaseAgeExclude:
  - xmldom@0.5.0
  - xmldom@0.6.1
  - merge@1.2.1
  - merge@2.1.1
  - fstream@1.0.12
  - esbuild@0.24.3
  - postcss@8.5.10
  - uuid@11.1.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
  - msw
  - sharp

overrides:
  esbuild@<=0.24.2: ^0.24.3
  fstream@<1.0.12: ^1.0.12
  merge@<1.2.1: ^1.2.1
  merge@<2.1.1: ^2.1.1
  postcss@<8.5.10: ^8.5.10
  uuid@<11.1.1: ^11.1.1
  xmldom@<0.5.0: ^0.5.0
  xmldom@<=0.6.0: ^0.6.1
